name: Create release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Zip Folder
      run: zip -r LA_BASE_DE_SKY_V${{github.ref_name}}.zip . -x ".git/*" ".github/*" ".gitignore" "LA BASE DE SKY/rgss-compiler.json", ".ruby-lsp/*"

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: LA_BASE_DE_SKY_V${{github.ref_name}}.zip
        generate_release_notes: true
        make_latest: true
        token: ${{ secrets.TOKEN_GITHUB }}